PowerShell/psl-omi-provider

.travis.yml
=> Fix Travis CI for public repo

src/Shell.c
This resolves the root cause of #28; and replaces https://github.com/PowerShell/PowerShell/pull/2201.
/cc @paulcallen @lilyfang @palladia
=> Fix HOME folder in impersonation scenarios

src/Client.c, src/Shell.c, src/coreclrutil.cpp
@palladia Pulling current Send code for piping data into a remote pipeline. Updates omi submodule too.
=> Shell send

.gitmodules
Hi, could you help to review and merge it? thank you!
=> Add Pester Submodule for PSRP

src/Client.c
it was not calling async callback in this situation
=> close session when creation failed hung

.gitignore, installbuilder/GNUmakefile, installbuilder/datafiles/Psrp.data, src/.gitignore
=> Changes for InstallBuilder for PAL submodule

.travis.yml, README.md
Update README.md along the way for new build process
@paulcallen
=> Fix Travis CI to use new GNU Makefile

installbuilder/GNUmakefile
=> Use Jenkins build number if possible for package version

.gitmodules, test/README.md
@andschwa could you help to review and merge it? thank you!
=> Fix issue 50 to remove Pester submodule

GNUmakefile, installbuilder/GNUmakefile, src/CMakeLists.txt
=> Fix rpath issues on mac

test/README.md, test/build.psm1, test/installPSRP.sh, test/installpowershell.sh, test/uninstallPSRP.sh
Could you help to review and merge it? thank you very much!
=> Add install and uninstall PSRP script for testing

installbuilder/nuget/libpsrpclient.nuspec
@jeffaco @palladia 
This is the file needed to generate a nuget package
=> add nuget nuspec file

test/PSRP.Tests.ps1, test/README.md, test/setPSRPTest.ps1, test/setPSRPTest.sh
Could you help to review and merge it? thank you!
=> Add Set Environment variables script for PSRP testing

test/README.md, test/installPSRP.sh
Could you help to review and merge? thank you very much!
=> Update installPSRP.sh script using interactive password

test/PSRP.Tests.ps1
Could you help to review and merge it? thank you very much!
=> Update PSRP.Tests.ps1 for Windows pass fixing

test/PSRP.Tests.ps1, test/build.psm1, test/installPSRP.sh
Could you help to review it? thanks very much!
=> Update PSRP Pester for Ubuntu16.04x64 pass

test/PSRP.Tests.ps1, test/README.md, test/build.psm1, test/installPSRP.sh, test/installpowershell.sh
@OpusDude , could you help to review this PR? thank you!
=> Add Negotiate authentication Pester Test

src/Client.c
Fixes issue #67
Note that http:// means port 80 and https:// means port 443 when
specified as a connection uri rather than just a computer name where it
defaults to the standard wsman port numbers.
@palladia @jeffaco @yakman2020
=> Fix full connection uri to support http://host:port/wsman-prefix

test/README.md, test/enableNTLM.sh, test/installPSRP.sh, test/uninstallPSRP.sh
Hi @OpusDude , could you help to review this PR? thank you!
=> Add enableNTLM script for PSRP test

src/Client.c
@yakman2020 @palladia @jeffaco
=> add ShellId option, encrypt by default

installbuilder/buildNuget.sh
=> Bump nuget version (and OMI dependency version)

GNUmakefile, installbuilder/GNUmakefile, src/CMakeLists.txt, src/Client.c
also fixed:
* warning needed fixing when I fixed build options to generate warnings as errors for C files
* fixed build number on psrp package file name 
* Cleaned up the psrp cmakelist.txt considerably
@Microsoft/omi-devs
=> Mainly to add a ulinux build option so the linux version works on different flavors of linux

test/build.psm1, test/installPSRP.sh, test/installpowershell.sh
Could you help to review this PR? thank you very much!
=> Update Pester test for PSRP to make pass on all platforms

README.md
=> Modify README.md to describe getting PSRP from MS Repo

test/PSRP.Tests.ps1
Could you help to review this PR? thank you very much!
=> Make Pester test more clear and breakdown them into serveral cases

test/PSRP.Tests.ps1, test/README.md, test/TestDesign/TestDesignSpecificationForPSRP.md
Could you help to review this PR? thanks very much!
=> Add TestDesign document for PSRP testing

test/README.md, test/TestDesign/TestDesignSpecificationForPSRP.md
There is some format issue in test readme, I have fixed it, could you help to review this PR? thanks very much!
=> Update test readme file

test/PSRP.Tests.ps1
Could you help to review this PR? thanks very much!
=> Delete cases related to omicli and winrm and add cases for invalid hostname scenarios
